'use client';
import {SiteLink,SiteAnchor,SiteImage} from './SiteContent';
import {SiteText} from './SiteContent';
import { useEffect,useRef,useState, type CSSProperties } from 'react';
import Link from 'next/link';
import { ArrowUpRight,Heart,Play,Pause,SkipForward,CalendarDays } from 'lucide-react';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Progress } from '@/components/ui/progress';
import { siteConfig,concerts,type Concert } from '@/lib/orchestra-data';
import {assetPath} from '@/lib/assets';

export function HeroVideo(){const [reduced,setReduced]=useState(true),[paused,setPaused]=useState(false);const video=useRef<HTMLVideoElement>(null);useEffect(()=>{const mq=matchMedia('(prefers-reduced-motion: reduce)');setReduced(mq.matches);const change=()=>setReduced(mq.matches);mq.addEventListener('change',change);return ()=>mq.removeEventListener('change',change)},[]);if(!siteConfig.heroVideoUrl||reduced)return null;return <><video ref={video} src={siteConfig.heroVideoUrl} muted autoPlay loop playsInline preload="metadata" aria-hidden="true"/><button className="absolute right-6 top-6 rounded border border-white/30 bg-black/40 px-3 py-2 text-sm" onClick={()=>{if(paused){video.current?.play().catch(()=>{})}else video.current?.pause();setPaused(!paused)}}><SiteText fallback={paused?'Play background':'Pause background'}/></button></>}

export function AudioPlayer(){const audio=useRef<HTMLAudioElement>(null);const [playing,setPlaying]=useState(false),[index,setIndex]=useState(0),[message,setMessage]=useState('');const track=siteConfig.tracks[index];const toggle=async()=>{if(!track){setMessage('Past state competition recordings will be available when approved school audio is added.');return;}try{if(playing)audio.current?.pause();else await audio.current?.play()}catch{setMessage('This recording could not be loaded. Please try again later.')}};return <><aside className="audio-player" aria-label="Orchestra audio player"><button aria-label={playing?'Pause recording':'Play recording'} onClick={toggle}>{playing?<Pause size={15}/>:<Play size={15}/>}</button><div><strong><SiteText fallback={track?.title||'The sound of McKay'}/></strong><span><SiteText fallback={track?.subtitle||'Performance recordings · Coming soon'}/></span></div><div className="bars" aria-hidden="true">{Array.from({length:7},(_,i)=><i key={i}/>)}</div>{siteConfig.tracks.length>1&&<button aria-label="Next recording" onClick={()=>{setIndex(i=>(i+1)%siteConfig.tracks.length);setPlaying(false)}}><SkipForward size={15}/></button>}<audio ref={audio} src={track?.url} preload="none" onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)} onError={()=>{setPlaying(false);setMessage('This recording is temporarily unavailable.')}}/></aside><Dialog open={!!message} onOpenChange={open=>{if(!open)setMessage('')}}><DialogContent><DialogTitle className="dialog-title"><SiteText fallback="Performance recordings"/></DialogTitle><DialogDescription className="dialog-copy"><SiteText fallback={message}/></DialogDescription></DialogContent></Dialog></>}

const stamp=(date:string)=>new Date(date).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');
const escapeIcs=(s:string)=>s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/[,;]/g,m=>'\\'+m);
export function googleCalendarUrl(event:Concert){return 'https://calendar.google.com/calendar/render?'+new URLSearchParams({action:'TEMPLATE',text:event.title,dates:`${stamp(event.start)}/${stamp(event.end)}`,location:event.location,details:'Illustrative event from the McKay website preview. Confirm real dates with the program.',ctz:'America/Los_Angeles'}).toString()}
export function downloadCalendar(events:Concert[]){const ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//McKay Preview//Concert Calendar//EN','CALSCALE:GREGORIAN',...events.flatMap(e=>['BEGIN:VEVENT',`UID:${e.id}-preview@mckayorchestras.com`,`DTSTAMP:${stamp(new Date().toISOString())}`,`DTSTART:${stamp(e.start)}`,`DTEND:${stamp(e.end)}`,`SUMMARY:${escapeIcs(e.title)}`,`LOCATION:${escapeIcs(e.location)}`,'DESCRIPTION:Sample preview event. Confirm dates with the program.','END:VEVENT']),'END:VCALENDAR'].join('\r\n');const url=URL.createObjectURL(new Blob([ics],{type:'text/calendar;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='mckay-preview-concerts.ics';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export function CalendarWidget(){const [event,setEvent]=useState<Concert|null>(null),[live,setLive]=useState(true);return <div className="calendar-widget"><div className="section-heading"><div><span className="eyebrow"><SiteText fallback="SAVE YOUR SEAT"/></span><h2><SiteText fallback="On the calendar."/></h2></div><CalendarDays size={24}/></div><div className="flex flex-wrap gap-3 mb-5"><button className="under-link" onClick={()=>setLive(!live)}><SiteText fallback={live?'Explore sample sync actions':'View live school calendar'}/></button><SiteLink href="/resources/calendar" className="under-link"><SiteText fallback="Subscribe to calendars ↗"/></SiteLink></div>{live&&siteConfig.calendarEmbedUrl?<><iframe title="Live McKay orchestra calendar" src={siteConfig.calendarEmbedUrl} loading="lazy" className="w-full h-[360px] rounded border-0 bg-white"/><p className="muted mt-3"><SiteText fallback="Published school calendar · If blocked, "/><SiteAnchor className="underline" href={siteConfig.calendarEmbedUrl} target="_blank" rel="noreferrer"><SiteText fallback="open calendar"/></SiteAnchor>.</p></>:<><p className="muted"><SiteText fallback="Preview schedule · Dates are illustrative"/></p>{concerts.map(e=><div className="event" key={e.id}><div className="date"><span><SiteText fallback={new Date(e.start).toLocaleDateString('en-US',{month:'short',timeZone:'America/Los_Angeles'})}/></span><b><SiteText fallback={new Date(e.start).toLocaleDateString('en-US',{day:'numeric',timeZone:'America/Los_Angeles'})}/></b></div><div><h3><SiteText fallback={e.title.replace(' (sample event)','')}/></h3><span><SiteText fallback="7:00 PM · McKay Auditorium"/></span></div><button className="ml-auto" aria-label={'Add '+e.title+' to calendar'} onClick={()=>setEvent(e)}><ArrowUpRight size={20}/></button></div>)}<button className="under-link mt-5" onClick={()=>downloadCalendar(concerts)}><SiteText fallback="Download all sample concerts (.ics)"/></button></>}<Dialog open={!!event} onOpenChange={open=>{if(!open)setEvent(null)}}><DialogContent><DialogTitle className="dialog-title"><SiteText fallback="Save your evening"/></DialogTitle><DialogDescription className="dialog-copy">{event?.title}<SiteText fallback=". This is a sample date for demonstrating calendar sync."/></DialogDescription>{event&&<div className="flex flex-wrap gap-3"><SiteAnchor className="button primary" href={googleCalendarUrl(event)} target="_blank" rel="noreferrer"><SiteText fallback="Google Calendar ↗"/></SiteAnchor><button className="button" onClick={()=>downloadCalendar([event])}><SiteText fallback="Apple / Outlook (.ics)"/></button></div>}</DialogContent></Dialog></div>}

export function FundraisingTracker(){const [burst,setBurst]=useState(0),[open,setOpen]=useState(false);const {raised,goal,isDemo}=siteConfig.campaign;const percent=Math.min(100,Math.round(raised/goal*100));return <div id="support" className="fundraiser"><Heart size={25} strokeWidth={1.5}/><span className="eyebrow"><SiteText fallback="HELP OUR NEXT CHAPTER"/></span><h2><SiteText fallback="A little support."/><br/><SiteText fallback="A lasting impact."/></h2><p><SiteText fallback="Help put new music on every stand."/></p><div className="fund-label"><b><SiteText fallback="New Sheet Music Fund"/></b><span>{percent}%</span></div><Progress value={percent} aria-label="Sheet music fundraising progress" className="h-1.5 bg-white/10 [&_[data-slot=progress-indicator]]:bg-[#91bd9b]"/><p className="mt-3"><strong>$<SiteText fallback={raised.toLocaleString()}/></strong> <span className="muted"><SiteText fallback="of $"/><SiteText fallback={goal.toLocaleString()}/> · <SiteText fallback={isDemo?'Sample campaign':'raised'}/></span></p><button className="button primary" onClick={()=>{setBurst(v=>v+1);setOpen(true)}}><SiteText fallback="Donate with PayPal "/><Heart size={16}/></button>{burst>0&&<div className="burst" key={burst} aria-hidden="true">{Array.from({length:18},(_,i)=><i key={i} style={{'--a':`${i*20}deg`} as CSSProperties}/>)}</div>}<Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogTitle className="dialog-title"><SiteText fallback="Help the music continue."/></DialogTitle><DialogDescription className="dialog-copy"><SiteText fallback="Thank you for supporting McKay. Continue to the program’s existing PayPal donation page. The campaign total shown in this design is illustrative; clicking does not record a donation."/></DialogDescription><SiteAnchor className="button primary" href={siteConfig.paypalUrl||siteConfig.officialUrl} target="_blank" rel="noreferrer"><SiteText fallback="Continue to PayPal "/><ArrowUpRight size={17}/></SiteAnchor></DialogContent></Dialog></div>}

const carouselImages=[
 {src:assetPath('/images/mckay-concert-stage.jpg'),alt:'McKay orchestra concert',caption:'Another amazing evening with the McKay Orchestras.'},
 {src:assetPath('/images/mckay-orchestra-group.jpg'),alt:'McKay orchestra students celebrating with their state championship award',caption:'Celebrating our 2025–26 third-place finish at the State Championships.'},
 {src:assetPath('/images/mckay-chicago.jpeg'),alt:'McKay orchestra group at Cloud Gate in Chicago',caption:'2024–25 Chicago Chamber Orchestra Trip.'},
 {src:assetPath('/images/mckay-forest-group.jpg'),alt:'McKay orchestra community gathered among tall trees',caption:'Silver Falls State Park Rehearsal & Bonding Trip.'},
 {src:assetPath('/images/mckay-beach-2026.jpeg'),alt:'McKay orchestra students together at the beach in Newport, Oregon',caption:'2025–26 Newport, Oregon Orchestra Festival Trip.'},
 {src:assetPath('/images/mckay-performance-2026.jpeg'),alt:'McKay orchestra performing together on stage',caption:'Every section. One sound.'},
 {src:assetPath('/images/mckay-state-2025.jpeg'),alt:'McKay orchestra performing at the OSAA State Championships',caption:'Taking the state stage.'},
];
export function ImageCarousel(){
 const [index,setIndex]=useState(0);
 const image=carouselImages[index];
 return <div className="image-carousel" role="region" aria-roledescription="carousel" aria-label="McKay orchestra gallery">
  <div className="carousel-frame"><SiteImage editable={false} src={image.src} alt={image.alt}/><span className="gallery-overline"><SiteText editable={false} fallback="LIFE AT McKAY"/></span></div>
  <div className="gallery-toolbar">
   <div className="gallery-description" aria-live="polite"><span><SiteText fallback={String(index+1).padStart(2,'0')}/> / <SiteText fallback={String(carouselImages.length).padStart(2,'0')}/></span><strong><SiteText fallback={image.caption}/></strong></div>
   <div className="gallery-controls"><button aria-label="Previous photo" onClick={()=>setIndex(i=>(i-1+carouselImages.length)%carouselImages.length)}>←</button><button aria-label="Next photo" onClick={()=>setIndex(i=>(i+1)%carouselImages.length)}>→</button></div>
  </div>
 </div>;
}

export function Widgets(){return <section className="support-gallery" aria-label="Support the music and explore our community"><div className="section-wrap support-gallery-inner"><FundraisingTracker/><ImageCarousel/></div></section>}

