'use client';
import { useEffect,useRef,useState, type CSSProperties } from 'react';
import Link from 'next/link';
import { ArrowUpRight,Heart,Play,Pause,SkipForward,CalendarDays } from 'lucide-react';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Progress } from '@/components/ui/progress';
import { siteConfig,concerts,type Concert } from '@/lib/orchestra-data';

export function HeroVideo(){const [reduced,setReduced]=useState(true),[paused,setPaused]=useState(false);const video=useRef<HTMLVideoElement>(null);useEffect(()=>{const mq=matchMedia('(prefers-reduced-motion: reduce)');setReduced(mq.matches);const change=()=>setReduced(mq.matches);mq.addEventListener('change',change);return ()=>mq.removeEventListener('change',change)},[]);if(!siteConfig.heroVideoUrl||reduced)return null;return <><video ref={video} src={siteConfig.heroVideoUrl} muted autoPlay loop playsInline preload="metadata" aria-hidden="true"/><button className="absolute right-6 top-6 rounded border border-white/30 bg-black/40 px-3 py-2 text-sm" onClick={()=>{if(paused){video.current?.play().catch(()=>{})}else video.current?.pause();setPaused(!paused)}}>{paused?'Play background':'Pause background'}</button></>}

export function AudioPlayer(){const audio=useRef<HTMLAudioElement>(null);const [playing,setPlaying]=useState(false),[index,setIndex]=useState(0),[message,setMessage]=useState('');const track=siteConfig.tracks[index];const toggle=async()=>{if(!track){setMessage('Past state competition recordings will be available when approved school audio is added.');return;}try{if(playing)audio.current?.pause();else await audio.current?.play()}catch{setMessage('This recording could not be loaded. Please try again later.')}};return <><aside className="audio-player" aria-label="Orchestra audio player"><button aria-label={playing?'Pause recording':'Play recording'} onClick={toggle}>{playing?<Pause size={15}/>:<Play size={15}/>}</button><div><strong>{track?.title||'The sound of McKay'}</strong><span>{track?.subtitle||'Performance recordings · Coming soon'}</span></div><div className="bars" aria-hidden="true">{Array.from({length:7},(_,i)=><i key={i}/>)}</div>{siteConfig.tracks.length>1&&<button aria-label="Next recording" onClick={()=>{setIndex(i=>(i+1)%siteConfig.tracks.length);setPlaying(false)}}><SkipForward size={15}/></button>}<audio ref={audio} src={track?.url} preload="none" onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)} onError={()=>{setPlaying(false);setMessage('This recording is temporarily unavailable.')}}/></aside><Dialog open={!!message} onOpenChange={open=>{if(!open)setMessage('')}}><DialogContent><DialogTitle className="dialog-title">Performance recordings</DialogTitle><DialogDescription className="dialog-copy">{message}</DialogDescription></DialogContent></Dialog></>}

const stamp=(date:string)=>new Date(date).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');
const escapeIcs=(s:string)=>s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/[,;]/g,m=>'\\'+m);
export function googleCalendarUrl(event:Concert){return 'https://calendar.google.com/calendar/render?'+new URLSearchParams({action:'TEMPLATE',text:event.title,dates:`${stamp(event.start)}/${stamp(event.end)}`,location:event.location,details:'Illustrative event from the McKay website preview. Confirm real dates with the program.',ctz:'America/Los_Angeles'}).toString()}
export function downloadCalendar(events:Concert[]){const ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//McKay Preview//Concert Calendar//EN','CALSCALE:GREGORIAN',...events.flatMap(e=>['BEGIN:VEVENT',`UID:${e.id}-preview@mckayorchestras.com`,`DTSTAMP:${stamp(new Date().toISOString())}`,`DTSTART:${stamp(e.start)}`,`DTEND:${stamp(e.end)}`,`SUMMARY:${escapeIcs(e.title)}`,`LOCATION:${escapeIcs(e.location)}`,'DESCRIPTION:Sample preview event. Confirm dates with the program.','END:VEVENT']),'END:VCALENDAR'].join('\r\n');const url=URL.createObjectURL(new Blob([ics],{type:'text/calendar;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='mckay-preview-concerts.ics';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export function CalendarWidget(){const [event,setEvent]=useState<Concert|null>(null),[live,setLive]=useState(true);return <div className="calendar-widget"><div className="section-heading"><div><span className="eyebrow">SAVE YOUR SEAT</span><h2>On the calendar.</h2></div><CalendarDays size={24}/></div><div className="flex flex-wrap gap-3 mb-5"><button className="under-link" onClick={()=>setLive(!live)}>{live?'Explore sample sync actions':'View live school calendar'}</button><Link href="/resources/calendar" className="under-link">Subscribe to calendars ↗</Link></div>{live&&siteConfig.calendarEmbedUrl?<><iframe title="Live McKay orchestra calendar" src={siteConfig.calendarEmbedUrl} loading="lazy" className="w-full h-[360px] rounded border-0 bg-white"/><p className="muted mt-3">Published school calendar · If blocked, <a className="underline" href={siteConfig.calendarEmbedUrl} target="_blank" rel="noreferrer">open calendar</a>.</p></>:<><p className="muted">Preview schedule · Dates are illustrative</p>{concerts.map(e=><div className="event" key={e.id}><div className="date"><span>{new Date(e.start).toLocaleDateString('en-US',{month:'short',timeZone:'America/Los_Angeles'})}</span><b>{new Date(e.start).toLocaleDateString('en-US',{day:'numeric',timeZone:'America/Los_Angeles'})}</b></div><div><h3>{e.title.replace(' (sample event)','')}</h3><span>7:00 PM · McKay Auditorium</span></div><button className="ml-auto" aria-label={'Add '+e.title+' to calendar'} onClick={()=>setEvent(e)}><ArrowUpRight size={20}/></button></div>)}<button className="under-link mt-5" onClick={()=>downloadCalendar(concerts)}>Download all sample concerts (.ics)</button></>}<Dialog open={!!event} onOpenChange={open=>{if(!open)setEvent(null)}}><DialogContent><DialogTitle className="dialog-title">Save your evening</DialogTitle><DialogDescription className="dialog-copy">{event?.title}. This is a sample date for demonstrating calendar sync.</DialogDescription>{event&&<div className="flex flex-wrap gap-3"><a className="button primary" href={googleCalendarUrl(event)} target="_blank" rel="noreferrer">Google Calendar ↗</a><button className="button" onClick={()=>downloadCalendar([event])}>Apple / Outlook (.ics)</button></div>}</DialogContent></Dialog></div>}

export function FundraisingTracker(){const [burst,setBurst]=useState(0),[open,setOpen]=useState(false);const {raised,goal,isDemo}=siteConfig.campaign;const percent=Math.min(100,Math.round(raised/goal*100));return <div id="support" className="fundraiser"><Heart size={25} strokeWidth={1.5}/><span className="eyebrow">HELP OUR NEXT CHAPTER</span><h2>A little support.<br/>A lasting impact.</h2><p>Help put new music on every stand.</p><div className="fund-label"><b>New Sheet Music Fund</b><span>{percent}%</span></div><Progress value={percent} aria-label="Sheet music fundraising progress" className="h-1.5 bg-white/10 [&_[data-slot=progress-indicator]]:bg-[#91bd9b]"/><p className="mt-3"><strong>${raised.toLocaleString()}</strong> <span className="muted">of ${goal.toLocaleString()} · {isDemo?'Sample campaign':'raised'}</span></p><button className="button primary" onClick={()=>{setBurst(v=>v+1);setOpen(true)}}>Donate with PayPal <Heart size={16}/></button>{burst>0&&<div className="burst" key={burst} aria-hidden="true">{Array.from({length:18},(_,i)=><i key={i} style={{'--a':`${i*20}deg`} as CSSProperties}/>)}</div>}<Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogTitle className="dialog-title">Help the music continue.</DialogTitle><DialogDescription className="dialog-copy">Thank you for supporting McKay. Continue to the program’s existing PayPal donation page. The campaign total shown in this design is illustrative; clicking does not record a donation.</DialogDescription><a className="button primary" href={siteConfig.paypalUrl||siteConfig.officialUrl} target="_blank" rel="noreferrer">Continue to PayPal <ArrowUpRight size={17}/></a></DialogContent></Dialog></div>}

export function SocialFeed(){const [loaded,setLoaded]=useState(false);const mount=useRef<HTMLDivElement>(null);useEffect(()=>{if(!loaded||!mount.current)return;const script=document.createElement('script');script.src='https://platform.twitter.com/widgets.js';script.async=true;mount.current.appendChild(script);return ()=>{script.remove();}},[loaded]);return <div className="social"><span className="eyebrow">LIFE BEYOND THE STAGE</span><h2>Stay in the loop.</h2><p>Rehearsals, milestones, and the moments in between. Follow @McKayOrchestras.</p>{!loaded?<button className="button" onClick={()=>setLoaded(true)}>Load live X / Twitter feed</button>:<div ref={mount}><a className="twitter-timeline" data-theme="dark" data-height="360" href={siteConfig.twitterProfileUrl}>Posts by @McKayOrchestras</a></div>}<a href={siteConfig.twitterProfileUrl} target="_blank" rel="noreferrer" className="under-link mt-4">Visit the official account <ArrowUpRight size={16}/></a><p className="muted">The embedded feed depends on X availability and browser privacy settings.</p></div>}
export function Widgets(){return <section className="section-wrap widgets" id="calendar"><CalendarWidget/><FundraisingTracker/><SocialFeed/></section>}
