'use client';
import {SiteLink,SiteAnchor,SiteImage} from './SiteContent';
import {SiteText} from './SiteContent';
import {useEffect,useState} from 'react';
import {Bell,CalendarDays,MapPin,Clock,Mail,Smartphone} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {previewEvents} from '@/lib/program-calendar';
import {watchEvents,type CalendarEvent} from '@/lib/calendar-store';

export default function ProgramCalendar(){
 const [liveEvents,setLiveEvents]=useState<CalendarEvent[]>([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(false);
 useEffect(()=>watchEvents(false,events=>{setLiveEvents(events);setLoading(false);setLoadError(false)},()=>{setLoading(false);setLoadError(true)}),[]);
 const [preview,setPreview]=useState(false),[filter,setFilter]=useState('All events'),[open,setOpen]=useState(false),[saved,setSaved]=useState(false);
 const [scope,setScope]=useState('All program events'),[channel,setChannel]=useState('Email'),[days,setDays]=useState('7'),[repeat,setRepeat]=useState('Once'),[time,setTime]=useState('09:00'),[zone,setZone]=useState('America/Los_Angeles');
 const source=preview?previewEvents:liveEvents;
 const events=source.filter(e=>filter==='All events'||e.category===filter).sort((a,b)=>a.startsAt.localeCompare(b.startsAt));
 const months=[...new Set(events.map(e=>e.startsAt.slice(0,7)))];
 const remind=(selection:string)=>{setScope(selection);setSaved(false);setOpen(true)};
 return <div className="program-calendar-page"><div className="program-calendar-heading"><span className="eyebrow"><SiteText fallback="2026–27 · THE YEAR IN MUSIC"/></span><h1><SiteText fallback="Every date."/><br/><em><SiteText fallback="Something to look forward to."/></em></h1><p><SiteText fallback="From the first rehearsal to the final bow. Find the year’s concerts, festivals, trips, and rehearsals in one place."/></p><button className="button primary calendar-reminder-cta" onClick={()=>remind('All program events')}><Bell size={17}/><SiteText fallback=" Customize reminders"/></button></div>
 <section className="year-schedule" aria-label="Annual program schedule"><div className="year-schedule-toolbar"><div><CalendarDays size={21}/><span><SiteText fallback="2026–27 season"/></span></div><span><SiteText fallback="All event times in Pacific time"/></span></div><div className="schedule-filters" aria-label="Filter events">{['All events','Concert','Festival','Trip','Rehearsal'].map(category=><button key={category} aria-pressed={filter===category} onClick={()=>setFilter(category)}><SiteText fallback={category==='All events'?category:category+'s'}/></button>)}</div>
 {preview&&<p className="schedule-preview-note"><SiteText fallback="Design preview · These example dates are not the official program schedule."/></p>}
 {!preview&&loading&&<p className="schedule-preview-note" role="status"><SiteText fallback="Loading program dates…"/></p>}
 {!preview&&loadError&&<p className="schedule-preview-note" role="status"><SiteText fallback="The schedule is temporarily unavailable. Please try again later."/></p>}
 {(!preview&&(loading||loadError))?null:events.length===0?<div className="schedule-empty"><CalendarDays size={34}/><h2><SiteText fallback={filter==='All events'?'The next chapter is taking shape.':'No '+filter.toLowerCase()+' dates published yet.'}/></h2><p><SiteText fallback="Confirmed dates will appear here when the program publishes its schedule."/></p></div>:months.map(month=><section key={month} className="schedule-month"><h2><SiteText fallback={new Date(month+'-15T12:00:00Z').toLocaleDateString('en-US',{month:'long',year:'numeric',timeZone:'America/Los_Angeles'})}/></h2>{events.filter(e=>e.startsAt.startsWith(month)).map(event=><article key={event.id} className="schedule-event"><div className="schedule-date"><strong><SiteText fallback={new Date(event.startsAt).toLocaleDateString('en-US',{day:'numeric',timeZone:'America/Los_Angeles'})}/></strong><span><SiteText fallback={new Date(event.startsAt).toLocaleDateString('en-US',{weekday:'short',timeZone:'America/Los_Angeles'})}/></span></div><div className="schedule-event-copy"><span className={'event-category category-'+event.category.toLowerCase()}><SiteText fallback={event.category}/></span><h3><SiteText fallback={event.title}/></h3><div className="schedule-event-meta"><span><Clock size={14}/><SiteText fallback={new Date(event.startsAt).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',timeZone:'America/Los_Angeles'})}/></span><span><MapPin size={14}/><SiteText fallback={event.location}/></span></div></div><button className="schedule-event-reminder" onClick={()=>remind(event.title)}><Bell size={16}/><span><SiteText fallback="Remind me"/></span></button></article>)}</section>)}
 <div className="schedule-demo-control"><button onClick={()=>{setPreview(!preview);setFilter('All events')}}><SiteText fallback={preview?'Return to program schedule':'Preview sample schedule'}/></button><span><SiteText fallback="Confirmed dates are published by the orchestra program."/></span></div></section>
 <section className="reminder-feature"><div className="reminder-feature-icon"><Bell size={25}/></div><div><span className="eyebrow"><SiteText fallback="YOUR SCHEDULE. YOUR REMINDERS."/></span><h2><SiteText fallback="A little heads-up goes a long way."/></h2><p><SiteText fallback="Choose how far ahead to be reminded, a preferred time, and whether to repeat until the event. Follow the entire program or a single event."/></p><div className="reminder-channel-labels"><span><Mail size={15}/><SiteText fallback=" Email"/></span><span><Smartphone size={15}/><SiteText fallback=" Text message"/></span></div></div><button className="button" onClick={()=>remind('All program events')}><SiteText fallback="Explore reminder settings"/></button></section>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="reminder-dialog"><DialogTitle className="dialog-title"><SiteText fallback="Your music. Your timing."/></DialogTitle><DialogDescription><SiteText fallback="Preview your reminder preferences. Email and text delivery are not connected yet; no messages will be sent."/></DialogDescription><form onChange={()=>setSaved(false)} onSubmit={event=>{event.preventDefault();try{localStorage.setItem('mckay-reminder-preview',JSON.stringify({scope,channel,days,repeat,time,zone}));setSaved(true)}catch{setSaved(false)}}} className="reminder-settings"><label><SiteText fallback="Follow"/><select value={scope} onChange={e=>setScope(e.target.value)}><option><SiteText fallback="All program events"/></option>{source.map(e=><option key={e.id}><SiteText fallback={e.title}/></option>)}</select></label><div className="reminder-settings-grid"><label><SiteText fallback="Delivery"/><select value={channel} onChange={e=>setChannel(e.target.value)}><option><SiteText fallback="Email"/></option><option><SiteText fallback="Text message"/></option><option><SiteText fallback="Email & text message"/></option></select></label><label><SiteText fallback="First reminder"/><select value={days} onChange={e=>setDays(e.target.value)}><option value="14"><SiteText fallback="Two weeks before"/></option><option value="7"><SiteText fallback="One week before"/></option><option value="3"><SiteText fallback="Three days before"/></option><option value="1"><SiteText fallback="One day before"/></option><option value="0"><SiteText fallback="On the day"/></option></select></label><label><SiteText fallback="Repeat until event"/><select value={repeat} onChange={e=>setRepeat(e.target.value)}><option><SiteText fallback="Once"/></option><option><SiteText fallback="Every day"/></option><option><SiteText fallback="Every two days"/></option></select></label><label><SiteText fallback="Preferred time"/><input type="time" required value={time} onChange={e=>setTime(e.target.value)}/></label></div><label><SiteText fallback="Your time zone"/><select value={zone} onChange={e=>setZone(e.target.value)}><option value="America/Los_Angeles"><SiteText fallback="Pacific time"/></option><option value="America/Denver"><SiteText fallback="Mountain time"/></option><option value="America/Chicago"><SiteText fallback="Central time"/></option><option value="America/New_York"><SiteText fallback="Eastern time"/></option><option value="Pacific/Honolulu"><SiteText fallback="Hawaii time"/></option><option value="America/Anchorage"><SiteText fallback="Alaska time"/></option></select></label><button type="submit" className="button primary"><SiteText fallback="Save preview preferences on this device"/></button>{saved&&<p role="status"><SiteText fallback="Preview preferences saved. You are not subscribed to reminders."/></p>}</form></DialogContent></Dialog></div>;
}
