'use client';
import {useState} from 'react';
import {Bell,CalendarDays,MapPin,Clock,Mail,Smartphone} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {programEvents,previewEvents} from '@/lib/program-calendar';

export default function ProgramCalendar(){
 const [preview,setPreview]=useState(false),[filter,setFilter]=useState('All events'),[open,setOpen]=useState(false),[saved,setSaved]=useState(false);
 const [scope,setScope]=useState('All program events'),[channel,setChannel]=useState('Email'),[days,setDays]=useState('7'),[repeat,setRepeat]=useState('Once'),[time,setTime]=useState('09:00'),[zone,setZone]=useState('America/Los_Angeles');
 const source=preview?previewEvents:programEvents;
 const events=source.filter(e=>filter==='All events'||e.category===filter).sort((a,b)=>a.startsAt.localeCompare(b.startsAt));
 const months=[...new Set(events.map(e=>e.startsAt.slice(0,7)))];
 const remind=(selection:string)=>{setScope(selection);setSaved(false);setOpen(true)};
 return <div className="program-calendar-page"><div className="program-calendar-heading"><span className="eyebrow">2026–27 · THE YEAR IN MUSIC</span><h1>Every date.<br/><em>Something to look forward to.</em></h1><p>From the first rehearsal to the final bow. Find the year’s concerts, festivals, trips, and rehearsals in one place.</p><button className="button primary calendar-reminder-cta" onClick={()=>remind('All program events')}><Bell size={17}/> Customize reminders</button></div>
 <section className="year-schedule" aria-label="Annual program schedule"><div className="year-schedule-toolbar"><div><CalendarDays size={21}/><span>2026–27 season</span></div><span>All event times in Pacific time</span></div><div className="schedule-filters" aria-label="Filter events">{['All events','Concert','Festival','Trip','Rehearsal'].map(category=><button key={category} aria-pressed={filter===category} onClick={()=>setFilter(category)}>{category==='All events'?category:category+'s'}</button>)}</div>
 {preview&&<p className="schedule-preview-note">Design preview · These example dates are not the official program schedule.</p>}
 {events.length===0?<div className="schedule-empty"><CalendarDays size={34}/><h2>{filter==='All events'?'The next chapter is taking shape.':'No '+filter.toLowerCase()+' dates published yet.'}</h2><p>Confirmed dates will appear here when the program publishes its schedule.</p></div>:months.map(month=><section key={month} className="schedule-month"><h2>{new Date(month+'-15T12:00:00Z').toLocaleDateString('en-US',{month:'long',year:'numeric',timeZone:'America/Los_Angeles'})}</h2>{events.filter(e=>e.startsAt.startsWith(month)).map(event=><article key={event.id} className="schedule-event"><div className="schedule-date"><strong>{new Date(event.startsAt).toLocaleDateString('en-US',{day:'numeric',timeZone:'America/Los_Angeles'})}</strong><span>{new Date(event.startsAt).toLocaleDateString('en-US',{weekday:'short',timeZone:'America/Los_Angeles'})}</span></div><div className="schedule-event-copy"><span className={'event-category category-'+event.category.toLowerCase()}>{event.category}</span><h3>{event.title}</h3><div className="schedule-event-meta"><span><Clock size={14}/>{new Date(event.startsAt).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',timeZone:'America/Los_Angeles'})}</span><span><MapPin size={14}/>{event.location}</span></div></div><button className="schedule-event-reminder" onClick={()=>remind(event.title)}><Bell size={16}/><span>Remind me</span></button></article>)}</section>)}
 <div className="schedule-demo-control"><button onClick={()=>{setPreview(!preview);setFilter('All events')}}>{preview?'Return to program schedule':'Preview sample schedule'}</button><span>Live event publishing is awaiting the admin backend.</span></div></section>
 <section className="reminder-feature"><div className="reminder-feature-icon"><Bell size={25}/></div><div><span className="eyebrow">YOUR SCHEDULE. YOUR REMINDERS.</span><h2>A little heads-up goes a long way.</h2><p>Choose how far ahead to be reminded, a preferred time, and whether to repeat until the event. Follow the entire program or a single event.</p><div className="reminder-channel-labels"><span><Mail size={15}/> Email</span><span><Smartphone size={15}/> Text message</span></div></div><button className="button" onClick={()=>remind('All program events')}>Explore reminder settings</button></section>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="reminder-dialog"><DialogTitle className="dialog-title">Your music. Your timing.</DialogTitle><DialogDescription>Preview your reminder preferences. Email and text delivery are not connected yet; no messages will be sent.</DialogDescription><form onChange={()=>setSaved(false)} onSubmit={event=>{event.preventDefault();try{localStorage.setItem('mckay-reminder-preview',JSON.stringify({scope,channel,days,repeat,time,zone}));setSaved(true)}catch{setSaved(false)}}} className="reminder-settings"><label>Follow<select value={scope} onChange={e=>setScope(e.target.value)}><option>All program events</option>{source.map(e=><option key={e.id}>{e.title}</option>)}</select></label><div className="reminder-settings-grid"><label>Delivery<select value={channel} onChange={e=>setChannel(e.target.value)}><option>Email</option><option>Text message</option><option>Email & text message</option></select></label><label>First reminder<select value={days} onChange={e=>setDays(e.target.value)}><option value="14">Two weeks before</option><option value="7">One week before</option><option value="3">Three days before</option><option value="1">One day before</option><option value="0">On the day</option></select></label><label>Repeat until event<select value={repeat} onChange={e=>setRepeat(e.target.value)}><option>Once</option><option>Every day</option><option>Every two days</option></select></label><label>Preferred time<input type="time" required value={time} onChange={e=>setTime(e.target.value)}/></label></div><label>Your time zone<select value={zone} onChange={e=>setZone(e.target.value)}><option value="America/Los_Angeles">Pacific time</option><option value="America/Denver">Mountain time</option><option value="America/Chicago">Central time</option><option value="America/New_York">Eastern time</option><option value="Pacific/Honolulu">Hawaii time</option><option value="America/Anchorage">Alaska time</option></select></label><button type="submit" className="button primary">Save preview preferences on this device</button>{saved&&<p role="status">Preview preferences saved. You are not subscribed to reminders.</p>}</form></DialogContent></Dialog></div>;
}
