'use client';
import Link from 'next/link';
import { Header,Footer } from './HomePage';
import { siteConfig } from '@/lib/orchestra-data';
export const resources:Record<string,{title:string;copy:string;url:string;label:string}>={
 handbook:{title:'Orchestra Handbook',copy:'Everything you need for a successful year of music. Read the current handbook on the official program website for expectations, concert attire, attendance, and policies.',url:'https://www.mckayorchestras.com/orchestra-handbook',label:'Read the current handbook'},
 elementary:{title:'Big futures start with first notes.',copy:'Explore elementary orchestra opportunities in the McKay community. The program’s official page has current school, teacher, and enrollment information.',url:'https://www.mckayorchestras.com/elementary-orchestra-info',label:'Elementary orchestra information'},
 contact:{title:'Let’s make a connection.',copy:'Questions about ensembles, performances, or joining the orchestra? Contact director Alex Figueroa using the details on the official program contact page.',url:'https://www.mckayorchestras.com/contact-us',label:'Contact the orchestra program'},
 auction:{title:'Something wonderful to bid on.',copy:'Explore the silent auction linked by the McKay orchestra program. Check the organizer’s page for current dates and availability.',url:'https://givebutter.com/c/mckay-music-program-silent-auction-May1st',label:'Early access silent auction'},
 donate:{title:'Keep the music growing.',copy:'Your support helps the McKay orchestra community. Use the program’s existing PayPal donation page to make a contribution.',url:'https://www.paypal.com/donate/?hosted_button_id=F4KB33NLGKSEE',label:'Donate with PayPal'},
 calendar:{title:'Never miss a performance.',copy:'Subscribe to the published school calendars below. Google and Apple will ask you to confirm the subscription. Availability depends on each calendar’s public sharing settings.',url:'https://www.mckayorchestras.com/calendar',label:'View the official calendar'}
};
const calendars=['4ks24hq1pf0l4r0c47eraantvs@group.calendar.google.com','8ru7jb2q0p5j759qmhak4772oo@group.calendar.google.com','ad72ih83dgq54dk8e87tltvp4s@group.calendar.google.com','c9ldttnkheqn2r6hfbv6n2k1kc@group.calendar.google.com','hcvg4jioi03sk46pcsen90eje0@group.calendar.google.com','k6gbin7dag6dpgkmsc6udvcle8@group.calendar.google.com','mckayhsorchestra@gmail.com'];
export function ResourcePage({slug}:{slug:string}){const r=resources[slug];return <><Header/><main className="resource"><Link className="eyebrow" href="/">← McKAY ORCHESTRAS</Link><h1>{r.title}</h1><p>{r.copy}</p><Link className="button primary" href={r.url} target="_blank" rel="noreferrer">{r.label} ↗</Link>{slug==='calendar'&&<div className="mt-8 space-y-5">{calendars.map((id,i)=><div key={id} className="flex flex-wrap items-center gap-4 border-b border-white/10 pb-4"><span>{i===6?'McKay orchestra calendar':`Program calendar ${i+1}`}</span><Link className="button" href={'https://calendar.google.com/calendar/u/0/r?cid='+encodeURIComponent(id)} target="_blank" rel="noreferrer">Add to Google</Link><Link className="button" href={'webcal://calendar.google.com/calendar/ical/'+encodeURIComponent(id)+'/public/basic.ics'}>Add to Apple</Link></div>)}<p className="muted">These seven calendar sources are carried over from the existing school site. Subscribe to the calendars relevant to your ensemble.</p></div>}</main><Footer/></>}
