'use client';
import Link from 'next/link';
import { Header,Footer } from './HomePage';
import ProgramCalendar from './ProgramCalendar';
import { HandbookContent, ElementaryContent, ContactContent } from './SchoolResources';
export const resources:Record<string,{title:string;copy:string;url:string;label:string}>={
 handbook:{title:'Orchestra Handbook',copy:'Everything you need for a successful year of music. Read the current handbook on the official program website for expectations, concert attire, attendance, and policies.',url:'https://www.mckayorchestras.com/orchestra-handbook',label:'Read the current handbook'},
 elementary:{title:'Big futures start with first notes.',copy:'Explore elementary orchestra opportunities in the McKay community. The program’s official page has current school, teacher, and enrollment information.',url:'https://www.mckayorchestras.com/elementary-orchestra-info',label:'Elementary orchestra information'},
 contact:{title:'Let’s make a connection.',copy:'Questions about ensembles, performances, or joining the orchestra? Contact director Alex Figueroa using the details on the official program contact page.',url:'https://www.mckayorchestras.com/contact-us',label:'Contact the orchestra program'},
 auction:{title:'Something wonderful to bid on.',copy:'Explore the silent auction linked by the McKay orchestra program. Check the organizer’s page for current dates and availability.',url:'https://givebutter.com/c/mckay-music-program-silent-auction-May1st',label:'Early access silent auction'},
 donate:{title:'Keep the music growing.',copy:'Your support helps the McKay orchestra community. Use the program’s existing PayPal donation page to make a contribution.',url:'https://www.paypal.com/donate/?hosted_button_id=F4KB33NLGKSEE',label:'Donate with PayPal'},
 calendar:{title:'Never miss a performance.',copy:'Subscribe to the published school calendars below. Google and Apple will ask you to confirm the subscription. Availability depends on each calendar’s public sharing settings.',url:'https://www.mckayorchestras.com/calendar',label:'View the official calendar'}
};
export function ResourcePage({slug}:{slug:string}){if(slug==='calendar')return <><Header/><main className="native-resource"><Link className="eyebrow back-link" href="/">← McKAY ORCHESTRAS</Link><ProgramCalendar/></main><Footer/></>;if(['handbook','elementary','contact'].includes(slug))return <><Header/><main className="native-resource"><Link className="eyebrow back-link" href="/">← McKAY ORCHESTRAS</Link>{slug==='handbook'?<HandbookContent/>:slug==='elementary'?<ElementaryContent/>:<ContactContent/>}</main><Footer/></>;const r=resources[slug];return <><Header/><main className="resource"><Link className="eyebrow" href="/">← McKAY ORCHESTRAS</Link><h1>{r.title}</h1><p>{r.copy}</p><Link className="button primary" href={r.url} target="_blank" rel="noreferrer">{r.label} ↗</Link></main><Footer/></>}