'use client';
import {createContext,useContext,useEffect,useRef,useState} from 'react';
import {Pencil,X,LockKeyhole} from 'lucide-react';
import {onAuthStateChanged,GoogleAuthProvider,signInWithPopup,signOut,type User} from 'firebase/auth';
import {doc,onSnapshot,runTransaction,serverTimestamp} from 'firebase/firestore';
import {firebaseServices} from '@/lib/firebase';
import Link from 'next/link';
import {assetPath} from '@/lib/assets';
export type SiteSettings={copy:Record<string,string>;links:Record<string,string>;assets:Record<string,string>;studentCount:number;enabledEnsembles:string[];version:number};
export const defaultSettings:SiteSettings={copy:{},links:{},assets:{},studentCount:150,enabledEnsembles:['chamber-ensemble','advanced-symphony','string-ensemble','concert-orchestra'],version:0};
type EditTarget={kind:'copy'|'assets'|'links'|'studentCount'|'enabledEnsembles';key:string;value:string;baseline?:string;items?:EditTarget[]};
function editBlock(element:Element){return element.closest('.audio-player,.fundraiser,.image-carousel,.ensemble-card,.concert-art,.concert-copy,.hero-facts>div,.stats>div,.section-heading,.brand,.support-link,.carousel-caption,.partner')??element.closest('h1,h2,h3,h4,p,a,button,label,summary')??element.parentElement??element}
const SiteContext=createContext({settings:defaultSettings,user:null as User|null,isAdmin:false,contentError:false,openEditor:(_target:EditTarget)=>{},openLogin:()=>{}});
export function SiteContentProvider({children}:{children:React.ReactNode}){
 const [settings,setSettings]=useState(defaultSettings),[user,setUser]=useState<User|null>(null),[isAdmin,setAdmin]=useState(false),[contentError,setError]=useState(false);
 const [target,setTarget]=useState<EditTarget|null>(null);
 const [loginOpen,setLoginOpen]=useState(false);
 useEffect(()=>{let sequence='',last=0;const keydown=(event:KeyboardEvent)=>{const element=event.target as HTMLElement;if(event.ctrlKey||event.metaKey||event.altKey||element.closest('input,textarea,select,[contenteditable="true"],dialog')||event.key.length!==1)return;if(Date.now()-last>3000)sequence='';last=Date.now();sequence=(sequence+event.key).slice(-4);if(sequence==='2026'){sequence='';setLoginOpen(true)}};window.addEventListener('keydown',keydown);return()=>window.removeEventListener('keydown',keydown)},[]);
 useEffect(()=>{if(!isAdmin)return;const group=()=>{const seen=new Set<Element>();document.querySelectorAll<HTMLElement>('[data-edit-target]').forEach(pencil=>{const block=editBlock(pencil);const secondary=seen.has(block);pencil.toggleAttribute('data-edit-secondary',secondary);pencil.tabIndex=secondary?-1:0;seen.add(block)})};group();const observer=new MutationObserver(group);observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect()},[isAdmin]);
 useEffect(()=>{const {auth,db}=firebaseServices();let stopAdmin:(()=>void)|undefined;const stopAuth=onAuthStateChanged(auth,current=>{stopAdmin?.();setUser(current);setAdmin(false);if(current)stopAdmin=onSnapshot(doc(db,'admins',current.uid),s=>setAdmin(current.emailVerified&&s.exists()),()=>setAdmin(false))});const stopContent=onSnapshot(doc(db,'site','content'),s=>{const data=s.data();if(data){const copy=Object.fromEntries(Object.entries(data.copy??{}).filter(([,v])=>typeof v==='string')) as Record<string,string>;setSettings({links:Object.fromEntries(Object.entries(data.links??{}).filter(([,v])=>typeof v==="string")) as Record<string,string>,assets:Object.fromEntries(Object.entries(data.assets??{}).filter(([,v])=>typeof v==="string")) as Record<string,string>,version:Number.isInteger(data.version)?data.version:0,copy,studentCount:Number.isInteger(data.studentCount)?data.studentCount:150,enabledEnsembles:Array.isArray(data.enabledEnsembles)?data.enabledEnsembles:defaultSettings.enabledEnsembles})}else setSettings(defaultSettings);setError(false)},()=>setError(true));return ()=>{stopAuth();stopAdmin?.();stopContent()}},[]);
 return <SiteContext.Provider value={{settings,user,isAdmin,contentError,openEditor:setTarget,openLogin:()=>setLoginOpen(true)}}>{children}{target&&isAdmin&&<InlineEditor target={target} close={()=>setTarget(null)}/>} {loginOpen&&<AdminSignIn close={()=>setLoginOpen(false)}/>}</SiteContext.Provider>;
}
export function useSiteContent(){return useContext(SiteContext)}
export function AdminLoginButton(){const {openLogin}=useSiteContent();return <button className="footer-admin-lock" aria-label="Administrator sign-in" title="Administrator sign-in" onClick={openLogin}><LockKeyhole size={14}/></button>}
function AdminSignIn({close}:{close:()=>void}){const {user,isAdmin}=useSiteContent();const dialog=useRef<HTMLDialogElement>(null),pending=useRef(false);const [busy,setBusy]=useState(false),[error,setError]=useState('');useEffect(()=>{dialog.current?.showModal()},[]);const login=async()=>{if(pending.current)return;pending.current=true;setBusy(true);setError('');try{const provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});await signInWithPopup(firebaseServices().auth,provider)}catch{setError('Sign-in could not complete. Allow the Google popup and try again.')}finally{pending.current=false;setBusy(false)}};return <dialog ref={dialog} className="inline-editor-dialog admin-sign-in-dialog" aria-label="Administrator sign-in" onCancel={e=>{e.preventDefault();if(!busy)close()}}><div className="inline-editor-heading"><h2>{isAdmin?'Website editing':'Administrator sign-in'}</h2><button aria-label="Close sign-in" disabled={busy} onClick={close}><X size={20}/></button></div><p>{isAdmin?'You’re signed in. Use the edit controls beside each content block.':user?'This account needs approval from the Firebase project owner.':'Sign in with your approved Google account to edit the website.'}</p>{user&&<p>{user.email}</p>}{error&&<p role="alert">{error}</p>}<div className="inline-editor-actions">{user&&<button className="button" disabled={busy} onClick={async()=>{setBusy(true);try{await signOut(firebaseServices().auth)}finally{setBusy(false)}}}>Sign out</button>}{isAdmin?<button className="button primary" onClick={close}>Start editing</button>:<button className="button primary" disabled={busy} onClick={login}>{busy?'Signing in…':user?'Use another Google account':'Sign in with Google'}</button>}</div></dialog>}
export function SiteText({fallback,editable=true,legacyParts}:{fallback:string;editable?:boolean;legacyParts?:string[]}){const {settings}=useSiteContent();const value=settings.copy[fallback]??(legacyParts?legacyParts.map(part=>settings.copy[part]??part).join(''):fallback);return <>{value.replaceAll("{{studentCount}}",String(settings.studentCount)).replaceAll("{{ensembleCount}}",String(settings.enabledEnsembles.length))}{editable&&<EditPencil target={{kind:'copy',key:fallback,value,baseline:settings.copy[fallback]??fallback}}/>}</>}
export function EditPencil({target}:{target:EditTarget}){const {isAdmin,openEditor}=useSiteContent();if(!isAdmin)return null;const open=(element:Element)=>{const block=editBlock(element);const unique=new Map<string,EditTarget>();block.querySelectorAll<HTMLElement>('[data-edit-target]').forEach(pencil=>{if(editBlock(pencil)!==block)return;const item=JSON.parse(pencil.dataset.editTarget!) as EditTarget;unique.set(`${item.kind}:${item.key}`,item)});const items=[...unique.values()];openEditor(items.length>1?{...target,items}:target)};return <span data-edit-target={JSON.stringify(target)} className="inline-edit-pencil" role="button" tabIndex={0} aria-label="Edit content block" title="Edit content block" onClick={e=>{e.preventDefault();e.stopPropagation();open(e.currentTarget)}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();open(e.currentTarget)}}}><Pencil size={12}/></span>}
export function SiteStat({kind}:{kind:'studentCount'|'enabledEnsembles'}){const {settings}=useSiteContent();return <>{kind==='studentCount'?`${settings.studentCount}+`:settings.enabledEnsembles.length}<EditPencil target={{kind,key:kind,value:kind==='studentCount'?String(settings.studentCount):settings.enabledEnsembles.join(',')}}/></>}
function InlineEditor({target,close}:{target:EditTarget;close:()=>void}){
 const {contentError}=useSiteContent();const dialog=useRef<HTMLDialogElement>(null);
 const items=target.items??[target];
 const [values,setValues]=useState(items.map(item=>item.value)),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{dialog.current?.showModal()},[]);
 const change=(index:number,value:string)=>setValues(previous=>previous.map((old,i)=>i===index?value:old));
 const save=async()=>{
  for(let i=0;i<items.length;i++){const item=items[i],value=values[i];if(item.kind==='studentCount'&&(!Number.isInteger(Number(value))||Number(value)<0||Number(value)>10000)){setError('Enter a whole student count between 0 and 10,000.');return}if((item.kind==='assets'||item.kind==='links')&&!safeSiteUrl(value)){setError('Enter a valid website URL or local path.');return}}
  setBusy(true);setError('');
  try{await runTransaction(firebaseServices().db,async tx=>{
   const ref=doc(firebaseServices().db,'site','content');const snapshot=await tx.get(ref);const latest={...defaultSettings,...snapshot.data()} as SiteSettings;
   items.forEach((item,i)=>{const value=values[i];if(item.kind==='copy'||item.kind==='assets'||item.kind==='links'){if((latest[item.kind][item.key]??item.key)!==(item.baseline??item.value))throw new Error('conflict');latest[item.kind]={...latest[item.kind],[item.key]:value}}else if(item.kind==='studentCount'){if(String(latest.studentCount)!==item.value)throw new Error('conflict');latest.studentCount=Number(value)}else{if(latest.enabledEnsembles.join(',')!==item.value)throw new Error('conflict');latest.enabledEnsembles=value.split(',').filter(Boolean)}});
   tx.set(ref,{...latest,version:latest.version+1,updatedAt:serverTimestamp()})
  });close()}catch(e){setError((e as Error).message==='conflict'?'This block changed while you were editing. Close and reopen to get the latest version.':'Could not save. Check your connection and published Firebase rules.')}finally{setBusy(false)}
 };
 const groups=[['chamber-ensemble','Chamber Ensemble'],['advanced-symphony','Advanced Symphony'],['string-ensemble','String Ensemble'],['concert-orchestra','Concert Orchestra']];
 const label=(item:EditTarget,index:number)=>item.kind==='copy'?(items.length>1?`Text ${index+1}`:'Your wording'):item.kind==='assets'?'Image URL':item.kind==='links'?'Link destination':item.kind==='studentCount'?'Student musicians':'Visible ensembles';
 return <dialog ref={dialog} className="inline-editor-dialog" aria-label="Edit website content" onCancel={e=>{e.preventDefault();if(!busy)close()}}><form onSubmit={e=>{e.preventDefault();save()}}><div className="inline-editor-heading"><h2>{items.length>1?'Edit content block':target.kind==='copy'?'Edit text':label(target,0)}</h2><button type="button" aria-label="Close editor" disabled={busy} onClick={close}><X size={20}/></button></div><div className="inline-editor-fields">{items.map((item,index)=>item.kind==='enabledEnsembles'?<fieldset key={`${item.kind}:${item.key}`}><legend>Visible ensembles</legend>{groups.map(([id,name])=><label key={id}><input type="checkbox" checked={values[index].split(',').includes(id)} onChange={e=>change(index,groups.map(([id])=>id).filter(slug=>slug===id?e.target.checked:values[index].split(',').includes(slug)).join(','))}/>{name}</label>)}</fieldset>:<label key={`${item.kind}:${item.key}`}>{label(item,index)}{item.kind==='copy'?<textarea autoFocus={index===0} rows={values[index].length>120?4:2} maxLength={5000} value={values[index]} onChange={e=>change(index,e.target.value)}/>:<input autoFocus={index===0} type={item.kind==='studentCount'?'number':'text'} value={values[index]} onChange={e=>change(index,e.target.value)}/>}</label>)}</div>{items.some(item=>item.value.includes('{{'))&&<p>Keep {'{{studentCount}}'} and {'{{ensembleCount}}'} to show automatic totals.</p>}{(error||contentError)&&<p role="alert">{error||'Publish the updated Firebase content rules before saving.'}</p>}<div className="inline-editor-actions"><button type="button" className="button" disabled={busy} onClick={close}>Cancel</button><button className="button primary" disabled={busy||contentError}>{busy?'Saving…':'Save block'}</button></div></form></dialog>
}
export function safeSiteUrl(value:string){return /^https?:\/\//i.test(value)||/^mailto:/i.test(value)||/^tel:/i.test(value)||/^webcal:\/\//i.test(value)||(/^\/(?!\/)/.test(value))||value.startsWith('#')}
export function SiteLink(props:React.ComponentProps<typeof Link>){const {settings}=useSiteContent();const original=typeof props.href==='string'?props.href:'';const replacement=settings.links[original];return <Link {...props} href={replacement&&safeSiteUrl(replacement)?replacement:props.href}>{props.children}{original&&<EditPencil target={{kind:'links',key:original,value:replacement??original}}/>}</Link>}
export function SiteAnchor(props:React.ComponentProps<'a'>){const {settings}=useSiteContent();const original=props.href??'';const replacement=settings.links[original];return <a {...props} href={replacement&&safeSiteUrl(replacement)?replacement:props.href}>{props.children}{original&&<EditPencil target={{kind:'links',key:original,value:replacement??original}}/>}</a>}
export function SiteImage(props:React.ComponentProps<'img'>){const {settings}=useSiteContent();const original=typeof props.src==='string'?props.src:'';const key=original.replace(/^\/McKay-HS-Orchestras(?=\/)/,'');const replacement=settings.assets[key];return <><img {...props} src={replacement&&safeSiteUrl(replacement)?(replacement.startsWith("/")?assetPath(replacement):replacement):props.src}/><EditPencil target={{kind:'assets',key,value:replacement??key}}/></>}



