'use client';
import {createContext,useContext,useEffect,useRef,useState} from 'react';
import {Pencil,X} from 'lucide-react';
import {onAuthStateChanged,type User} from 'firebase/auth';
import {doc,onSnapshot,runTransaction,serverTimestamp} from 'firebase/firestore';
import {firebaseServices} from '@/lib/firebase';
import Link from 'next/link';
import {assetPath} from '@/lib/assets';
export type SiteSettings={copy:Record<string,string>;links:Record<string,string>;assets:Record<string,string>;studentCount:number;enabledEnsembles:string[];version:number};
export const defaultSettings:SiteSettings={copy:{},links:{},assets:{},studentCount:150,enabledEnsembles:['chamber-ensemble','advanced-symphony','string-ensemble','concert-orchestra'],version:0};
type EditTarget={kind:'copy'|'assets'|'links'|'studentCount'|'enabledEnsembles';key:string;value:string};
const SiteContext=createContext({settings:defaultSettings,user:null as User|null,isAdmin:false,contentError:false,openEditor:(_target:EditTarget)=>{}});
export function SiteContentProvider({children}:{children:React.ReactNode}){
 const [settings,setSettings]=useState(defaultSettings),[user,setUser]=useState<User|null>(null),[isAdmin,setAdmin]=useState(false),[contentError,setError]=useState(false);
 const [target,setTarget]=useState<EditTarget|null>(null);
 useEffect(()=>{const {auth,db}=firebaseServices();let stopAdmin:(()=>void)|undefined;const stopAuth=onAuthStateChanged(auth,current=>{stopAdmin?.();setUser(current);setAdmin(false);if(current)stopAdmin=onSnapshot(doc(db,'admins',current.uid),s=>setAdmin(current.emailVerified&&s.exists()),()=>setAdmin(false))});const stopContent=onSnapshot(doc(db,'site','content'),s=>{const data=s.data();if(data){const copy=Object.fromEntries(Object.entries(data.copy??{}).filter(([,v])=>typeof v==='string')) as Record<string,string>;setSettings({links:Object.fromEntries(Object.entries(data.links??{}).filter(([,v])=>typeof v==="string")) as Record<string,string>,assets:Object.fromEntries(Object.entries(data.assets??{}).filter(([,v])=>typeof v==="string")) as Record<string,string>,version:Number.isInteger(data.version)?data.version:0,copy,studentCount:Number.isInteger(data.studentCount)?data.studentCount:150,enabledEnsembles:Array.isArray(data.enabledEnsembles)?data.enabledEnsembles:defaultSettings.enabledEnsembles})}else setSettings(defaultSettings);setError(false)},()=>setError(true));return ()=>{stopAuth();stopAdmin?.();stopContent()}},[]);
 return <SiteContext.Provider value={{settings,user,isAdmin,contentError,openEditor:setTarget}}>{children}{target&&isAdmin&&<InlineEditor target={target} close={()=>setTarget(null)}/>}</SiteContext.Provider>;
}
export function useSiteContent(){return useContext(SiteContext)}
export function SiteText({fallback,editable=true}:{fallback:string;editable?:boolean}){const {settings}=useSiteContent();return <>{(settings.copy[fallback]??fallback).replaceAll("{{studentCount}}",String(settings.studentCount)).replaceAll("{{ensembleCount}}",String(settings.enabledEnsembles.length))}{editable&&<EditPencil target={{kind:'copy',key:fallback,value:settings.copy[fallback]??fallback}}/>}</>}
export function EditPencil({target}:{target:EditTarget}){const {isAdmin,openEditor}=useSiteContent();if(!isAdmin)return null;return <span className="inline-edit-pencil" role="button" tabIndex={0} aria-label={`Edit ${target.kind==='copy'?'text':target.kind}`} title="Edit" onClick={e=>{e.preventDefault();e.stopPropagation();openEditor(target)}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();openEditor(target)}}}><Pencil size={12}/></span>}
export function SiteStat({kind}:{kind:'studentCount'|'enabledEnsembles'}){const {settings}=useSiteContent();return <>{kind==='studentCount'?`${settings.studentCount}+`:settings.enabledEnsembles.length}<EditPencil target={{kind,key:kind,value:kind==='studentCount'?String(settings.studentCount):settings.enabledEnsembles.join(',')}}/></>}
function InlineEditor({target,close}:{target:EditTarget;close:()=>void}){
 const {settings,contentError}=useSiteContent();const dialog=useRef<HTMLDialogElement>(null);const [value,setValue]=useState(target.value),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{dialog.current?.showModal()},[]);
 const save=async()=>{if(target.kind==='studentCount'&&(!Number.isInteger(Number(value))||Number(value)<0||Number(value)>10000)){setError('Enter a whole number between 0 and 10,000.');return}if((target.kind==='assets'||target.kind==='links')&&!safeSiteUrl(value)){setError('Enter a valid website URL or local path.');return}setBusy(true);setError('');try{await runTransaction(firebaseServices().db,async tx=>{const ref=doc(firebaseServices().db,'site','content');const snapshot=await tx.get(ref);const latest={...defaultSettings,...snapshot.data()} as SiteSettings;if(target.kind==='copy'||target.kind==='assets'||target.kind==='links'){if((latest[target.kind][target.key]??target.key)!==target.value)throw new Error('conflict');latest[target.kind]={...latest[target.kind],[target.key]:value}}else if(target.kind==='studentCount')latest.studentCount=Number(value);else latest.enabledEnsembles=value.split(',').filter(Boolean);tx.set(ref,{...latest,version:latest.version+1,updatedAt:serverTimestamp()})});close()}catch(e){setError((e as Error).message==='conflict'?'This item changed while you were editing. Close and reopen to get the latest version.':'Could not save. Check your connection and published Firebase rules.')}finally{setBusy(false)}};
 const groups=[['chamber-ensemble','Chamber Ensemble'],['advanced-symphony','Advanced Symphony'],['string-ensemble','String Ensemble'],['concert-orchestra','Concert Orchestra']];
 return <dialog ref={dialog} className="inline-editor-dialog" onCancel={e=>{e.preventDefault();if(!busy)close()}}><form onSubmit={e=>{e.preventDefault();save()}}><div className="inline-editor-heading"><h2>{target.kind==='copy'?'Edit text':target.kind==='assets'?'Change image':target.kind==='links'?'Edit link':target.kind==='studentCount'?'Student musicians':'Visible ensembles'}</h2><button type="button" aria-label="Close editor" disabled={busy} onClick={close}><X size={20}/></button></div>{target.kind==='enabledEnsembles'?<fieldset>{groups.map(([id,name])=><label key={id}><input type="checkbox" checked={value.split(',').includes(id)} onChange={e=>setValue(groups.map(([id])=>id).filter(slug=>slug===id?e.target.checked:value.split(',').includes(slug)).join(','))}/>{name}</label>)}</fieldset>:<label>{target.kind==='copy'?'Your wording':target.kind==='studentCount'?'Total students':'URL'}{target.kind==='copy'?<textarea autoFocus rows={5} maxLength={5000} value={value} onChange={e=>setValue(e.target.value)}/>:<input autoFocus type={target.kind==='studentCount'?'number':'text'} value={value} onChange={e=>setValue(e.target.value)}/>}</label>}{target.kind==='copy'&&(target.value.includes('{{'))&&<p>Keep {'{{studentCount}}'} and {'{{ensembleCount}}'} to show automatic totals.</p>}{(error||contentError)&&<p role="alert">{error||'Publish the updated Firebase content rules before saving.'}</p>}<div className="inline-editor-actions"><button type="button" className="button" disabled={busy} onClick={close}>Cancel</button><button className="button primary" disabled={busy||contentError}>{busy?'Saving…':'Save changes'}</button></div></form></dialog>
}
export function safeSiteUrl(value:string){return /^https?:\/\//i.test(value)||/^mailto:/i.test(value)||/^tel:/i.test(value)||/^webcal:\/\//i.test(value)||(/^\/(?!\/)/.test(value))||value.startsWith('#')}
export function SiteLink(props:React.ComponentProps<typeof Link>){const {settings}=useSiteContent();const original=typeof props.href==='string'?props.href:'';const replacement=settings.links[original];return <Link {...props} href={replacement&&safeSiteUrl(replacement)?replacement:props.href}>{props.children}{original&&<EditPencil target={{kind:'links',key:original,value:replacement??original}}/>}</Link>}
export function SiteAnchor(props:React.ComponentProps<'a'>){const {settings}=useSiteContent();const original=props.href??'';const replacement=settings.links[original];return <a {...props} href={replacement&&safeSiteUrl(replacement)?replacement:props.href}>{props.children}{original&&<EditPencil target={{kind:'links',key:original,value:replacement??original}}/>}</a>}
export function SiteImage(props:React.ComponentProps<'img'>){const {settings}=useSiteContent();const original=typeof props.src==='string'?props.src:'';const key=original.replace(/^\/McKay-HS-Orchestras(?=\/)/,'');const replacement=settings.assets[key];return <><img {...props} src={replacement&&safeSiteUrl(replacement)?(replacement.startsWith("/")?assetPath(replacement):replacement):props.src}/><EditPencil target={{kind:'assets',key,value:replacement??key}}/></>}

