type Teacher={name:string;email:string};
type ClassInfo={grade:string;teachers:Teacher[];schedule:string[];location?:string;starts:string};
export type SchoolInfo={classes:ClassInfo[];transport?:string[]};
const tyler={name:'Tyler Goldman',email:'goldman_tyler@salkeiz.k12.or.us'};
const deborah={name:'Deborah Barber',email:'barber_deborah@salkeiz.k12.or.us'};
const kyle={name:'Kyle Lissman',email:'lissman_kyle@salkeiz.k12.or.us'};
const kit={name:'Dr. Kit',email:'abrahamson_kit@salkeiz.k12.or.us'};
const middle=(teachers:Teacher[],location:string,starts='September 18th'):ClassInfo=>({grade:'5th grade',teachers,schedule:['Monday–Friday · 3:00–4:00 PM'],location,starts});
const transport=(school:string,middleSchool:string)=>[`Students ride a bus from ${school} to ${middleSchool} after elementary school.`,`After orchestra, students may walk home, be picked up, or take the middle school bus home.`];
export const schoolDetails:Record<string,SchoolInfo>={
 AUBURN:{classes:[{grade:'4th grade',teachers:[tyler],schedule:['Tuesday · Recess','Thursday · Recess','Friday · 2:20–2:50'],starts:'September 18th'},middle([{name:'Juana Gutierrez Duran',email:'gutierrezduran_juana@salkeiz.k12.or.us'}],'Houck Middle School','September 20th')],transport:transport('Auburn','Houck')},
 CHAVEZ:{classes:[{grade:'4th grade',teachers:[tyler],schedule:['Tuesday · Recess','Wednesday · 2:20–2:50','Thursday · Recess'],starts:'September 18th'},middle([deborah],'Waldo Middle School · Waldo area','Thursday, September 18th'),middle([kyle],'Stephens Middle School · Stephens area','Thursday, September 18th')],transport:transport('Chavez','their middle school')},
 HALLMAN:{classes:[{grade:'4th grade',teachers:[deborah],schedule:['Monday · 11:30–12:00 · Lunch/recess','Wednesday · 8:00–8:40 · Before school','Thursday · 11:30–12:00 · Lunch/recess'],location:'Hallman Music',starts:'September 15th'},middle([deborah],'Waldo Middle School')],transport:['Students ride a bus from Hallman to Waldo after elementary school.','After orchestra: walk home, be picked up, take a middle school bus home if available, or take the middle school bus to Hallman.']},
 HAMMOND:{classes:[{grade:'4th grade',teachers:[{name:'Juan Sebastian Lopez Mahecha',email:'lopezmahecha_juansebastian@salkeiz.k12.or.us'}],schedule:['Monday · 8:10–8:40','Wednesday · 9:10–9:40','Thursday · 8:10–8:40'],location:'Portable room D-2',starts:'Monday, September 23th (as printed)'},middle([kyle,tyler],'Stephens Middle School','Thursday, September 18th')],transport:transport('Hammond','Stephens')},
 HAYESVILLE:{classes:[{grade:'4th grade',teachers:[kit],schedule:['Tuesday, Wednesday & Thursday · 12:20–12:50'],location:'Hayesville Cafeteria',starts:'Tuesday, September 23th (as printed)'},middle([kyle,tyler],'Stephens Middle School','Thursday, September 18th')],transport:transport('Hayesville','Stephens')},
 LAMB:{classes:[{grade:'4th grade',teachers:[tyler],schedule:['Monday, Tuesday & Thursday · 8:30–9:00'],starts:'September 19th'},{grade:'5th grade',teachers:[tyler],schedule:['Monday · 7:40–8:25','Tuesday · 7:40–8:25','Wednesday · 9:15–10:00','Thursday · 7:40–8:25','Friday · 8:15–9:00'],starts:'September 18th'}]},
 SCOTT:{classes:[{grade:'4th grade',teachers:[tyler],schedule:['Monday · 2:20–2:50','Tuesday · 2:20–2:50','Wednesday · Recess'],starts:'September 22nd'},middle([deborah],'Waldo Middle School')],transport:transport('Scott','Waldo')},
 SWEGLE:{classes:[{grade:'4th grade',teachers:[deborah],schedule:['Tuesday, Wednesday & Friday · 12:00–12:30 · Recess'],location:'Room 5, Swegle',starts:'September 16th'},middle([deborah],'Waldo Middle School')],transport:['Students ride a bus from Swegle to Waldo after elementary school.','After orchestra: walk home, be picked up, take a middle school bus home if available, or take the middle school bus to Swegle.']},
 WASHINGTON:{classes:[{grade:'4th grade',teachers:[tyler],schedule:['Monday · Recess','Thursday · 2:20–2:50','Friday · Recess'],starts:'September 18th'},middle([deborah],'Waldo Middle School')],transport:['Students walk from Washington to Waldo after elementary school.','After orchestra, students may walk home or be picked up.']},
 YOSHIKAI:{classes:[{grade:'4th grade',teachers:[kit],schedule:['Monday · 12:00–12:30 · Recess','Wednesday · 8:15–8:45','Friday · 12:00–12:30 · Recess'],location:'Yoshikai Orchestra Room',starts:'Monday, September 22nd'},middle([kyle,tyler],'Stephens Middle School','Thursday, September 18th')],transport:transport('Yoshikai','Stephens')},
};
